<?php

return [
    'ACADEMY_PROFILE_REQUIRED' => ['status' => 422, 'category' => 'course', 'retryable' => false, 'messageEn' => 'Complete the academy profile before publishing courses.', 'messageAr' => 'أكمل ملف الأكاديمية قبل نشر الكورسات.'],
    'ACCOUNT_DISABLED' => ['status' => 403, 'category' => 'auth', 'retryable' => false, 'messageEn' => 'This account is not available.', 'messageAr' => 'هذا الحساب غير متاح.'],
    'AUTHENTICATION_REQUIRED' => ['status' => 401, 'category' => 'auth', 'retryable' => false, 'messageEn' => 'Sign in to continue.', 'messageAr' => 'سجل الدخول للمتابعة.'],
    'BATCH_NOT_BOOKABLE' => ['status' => 409, 'category' => 'booking', 'retryable' => false, 'messageEn' => 'This batch is not open for booking.', 'messageAr' => 'هذه الدفعة غير متاحة للحجز.'],
    'BOOKING_ALREADY_EXISTS' => ['status' => 409, 'category' => 'booking', 'retryable' => false, 'messageEn' => 'You already have a booking for this course.', 'messageAr' => 'لديك حجز لهذا الكورس بالفعل.'],
    'BOOKING_EMAIL_MISMATCH' => ['status' => 403, 'category' => 'booking', 'retryable' => false, 'messageEn' => 'This booking belongs to another email address.', 'messageAr' => 'هذا الحجز مرتبط ببريد إلكتروني آخر.'],
    'BOOKING_INVALID_STATE' => ['status' => 409, 'category' => 'booking', 'retryable' => false, 'messageEn' => 'This booking cannot be changed in its current state.', 'messageAr' => 'لا يمكن تعديل هذا الحجز في حالته الحالية.'],
    'BOOKING_NOT_CANCELLABLE' => ['status' => 409, 'category' => 'booking', 'retryable' => false, 'messageEn' => 'This booking can no longer be cancelled.', 'messageAr' => 'لم يعد من الممكن إلغاء هذا الحجز.'],
    'CAPACITY_FULL' => ['status' => 409, 'category' => 'booking', 'retryable' => true, 'messageEn' => 'This batch is full.', 'messageAr' => 'اكتمل عدد المقاعد في هذه الدفعة.'],
    'CATEGORY_IN_USE' => ['status' => 409, 'category' => 'admin', 'retryable' => false, 'messageEn' => 'This category is currently in use.', 'messageAr' => 'هذا التصنيف مستخدم حاليًا.'],
    'CATEGORY_PARENT_INVALID' => ['status' => 422, 'category' => 'admin', 'retryable' => false, 'messageEn' => 'Choose a valid parent category.', 'messageAr' => 'اختر تصنيفًا رئيسيًا صالحًا.'],
    'CONTENT_ACCESS_EXPIRED' => ['status' => 403, 'category' => 'content', 'retryable' => false, 'messageEn' => 'Access to this content is no longer available.', 'messageAr' => 'لم يعد الوصول لهذا المحتوى متاحًا.'],
    'CONTENT_NOT_AVAILABLE' => ['status' => 409, 'category' => 'content', 'retryable' => true, 'messageEn' => 'This content is not available yet.', 'messageAr' => 'هذا المحتوى غير متاح بعد.'],
    'COURSE_INCOMPLETE' => ['status' => 422, 'category' => 'course', 'retryable' => false, 'messageEn' => 'Complete the course details before submitting it.', 'messageAr' => 'أكمل بيانات الكورس قبل إرساله.'],
    'COURSE_INVALID_STATE' => ['status' => 409, 'category' => 'course', 'retryable' => false, 'messageEn' => 'This course cannot be changed in its current state.', 'messageAr' => 'لا يمكن تعديل هذا الكورس في حالته الحالية.'],
    'COURSE_NOT_BOOKABLE' => ['status' => 409, 'category' => 'booking', 'retryable' => false, 'messageEn' => 'This course is not available for booking.', 'messageAr' => 'هذا الكورس غير متاح للحجز.'],
    'COURSE_NOT_EDITABLE' => ['status' => 409, 'category' => 'course', 'retryable' => false, 'messageEn' => 'This course cannot be edited now.', 'messageAr' => 'لا يمكن تعديل هذا الكورس الآن.'],
    'CURRENT_PASSWORD_INCORRECT' => ['status' => 422, 'category' => 'auth', 'retryable' => false, 'messageEn' => 'The current password is incorrect.', 'messageAr' => 'كلمة المرور الحالية غير صحيحة.'],
    'DELETION_REQUEST_NOT_FOUND' => ['status' => 404, 'category' => 'privacy', 'retryable' => false, 'messageEn' => 'No active deletion request was found.', 'messageAr' => 'لا يوجد طلب حذف نشط.'],
    'DEVICE_LIMIT_REACHED' => ['status' => 403, 'category' => 'device', 'retryable' => false, 'messageEn' => 'Too many active devices. Revoke a device session and try again.', 'messageAr' => 'عدد الأجهزة النشطة كبير جدًا. ألغِ جلسة جهاز وحاول مرة أخرى.'],
    'DOWNLOAD_DISABLED' => ['status' => 403, 'category' => 'content', 'retryable' => false, 'messageEn' => 'Downloading is disabled for this content.', 'messageAr' => 'تنزيل هذا المحتوى غير مسموح.'],
    'EMAIL_NOT_VERIFIED' => ['status' => 403, 'category' => 'auth', 'retryable' => false, 'messageEn' => 'Verify your email before signing in.', 'messageAr' => 'فعّل بريدك الإلكتروني قبل تسجيل الدخول.'],
    'ENROLLMENT_CLOSED' => ['status' => 409, 'category' => 'booking', 'retryable' => false, 'messageEn' => 'Enrollment is closed for this batch.', 'messageAr' => 'تم إغلاق التسجيل في هذه الدفعة.'],
    'FILE_UPLOAD_FAILED' => ['status' => 500, 'category' => 'content', 'retryable' => true, 'messageEn' => 'The file could not be uploaded.', 'messageAr' => 'تعذر رفع الملف.'],
    'FORBIDDEN' => ['status' => 403, 'category' => 'authorization', 'retryable' => false, 'messageEn' => 'You do not have permission to do this.', 'messageAr' => 'ليست لديك صلاحية لتنفيذ هذا الإجراء.'],
    'IDEMPOTENCY_KEY_CONFLICT' => ['status' => 409, 'category' => 'request', 'retryable' => false, 'messageEn' => 'This request key was already used with different data.', 'messageAr' => 'تم استخدام مفتاح الطلب من قبل ببيانات مختلفة.'],
    'INTERNAL_SERVER_ERROR' => ['status' => 500, 'category' => 'system', 'retryable' => true, 'messageEn' => 'Something went wrong. Please try again.', 'messageAr' => 'حدث خطأ غير متوقع. حاول مرة أخرى.'],
    'INVALID_CODE' => ['status' => 422, 'category' => 'auth', 'retryable' => false, 'messageEn' => 'The verification code is invalid or expired.', 'messageAr' => 'رمز التحقق غير صحيح أو منتهي الصلاحية.'],
    'INVALID_CREDENTIALS' => ['status' => 401, 'category' => 'auth', 'retryable' => false, 'messageEn' => 'Email or password is incorrect.', 'messageAr' => 'البريد الإلكتروني أو كلمة المرور غير صحيحة.'],
    'INVITATION_ALREADY_PENDING' => ['status' => 409, 'category' => 'invitation', 'retryable' => false, 'messageEn' => 'An invitation is already pending for this email.', 'messageAr' => 'توجد دعوة معلقة لهذا البريد بالفعل.'],
    'INVITATION_EMAIL_MISMATCH' => ['status' => 403, 'category' => 'invitation', 'retryable' => false, 'messageEn' => 'This invitation was sent to another email address.', 'messageAr' => 'هذه الدعوة مرسلة إلى بريد إلكتروني آخر.'],
    'INVITATION_EXPIRED' => ['status' => 410, 'category' => 'invitation', 'retryable' => false, 'messageEn' => 'This invitation is invalid or expired.', 'messageAr' => 'هذه الدعوة غير صالحة أو منتهية الصلاحية.'],
    'INVITATION_INVALID' => ['status' => 404, 'category' => 'invitation', 'retryable' => false, 'messageEn' => 'This invitation could not be found.', 'messageAr' => 'تعذر العثور على هذه الدعوة.'],
    'INVITATION_NOT_CANCELLABLE' => ['status' => 409, 'category' => 'invitation', 'retryable' => false, 'messageEn' => 'This invitation cannot be cancelled.', 'messageAr' => 'لا يمكن إلغاء هذه الدعوة.'],
    'INVITATION_NOT_RESENDABLE' => ['status' => 409, 'category' => 'invitation', 'retryable' => false, 'messageEn' => 'This invitation cannot be resent.', 'messageAr' => 'لا يمكن إعادة إرسال هذه الدعوة.'],
    'LAST_OWNER_REQUIRED' => ['status' => 409, 'category' => 'members', 'retryable' => false, 'messageEn' => 'Every organization must keep at least one owner.', 'messageAr' => 'يجب أن تحتفظ كل مؤسسة بمالك واحد على الأقل.'],
    'MEMBER_ALREADY_EXISTS' => ['status' => 409, 'category' => 'members', 'retryable' => false, 'messageEn' => 'This user is already a member.', 'messageAr' => 'هذا المستخدم عضو بالفعل.'],
    'MODERATION_NOTE_REQUIRED' => ['status' => 422, 'category' => 'moderation', 'retryable' => false, 'messageEn' => 'Add a moderation note before rejecting.', 'messageAr' => 'أضف ملاحظة مراجعة قبل الرفض.'],
    'MODULE_DISABLED' => ['status' => 403, 'category' => 'plan', 'retryable' => false, 'messageEn' => 'This module is not enabled for the current plan.', 'messageAr' => 'هذه الوحدة غير مفعلة في الخطة الحالية.'],
    'ORGANIZATION_SUSPENDED' => ['status' => 403, 'category' => 'workspace', 'retryable' => false, 'messageEn' => 'This organization is currently suspended.', 'messageAr' => 'هذه المؤسسة موقوفة حاليًا.'],
    'PAYMENTS_DISABLED' => ['status' => 503, 'category' => 'payments', 'retryable' => true, 'messageEn' => 'Payments are not available right now.', 'messageAr' => 'الدفع غير متاح حاليًا.'],
    'PLAN_LIMIT_REACHED' => ['status' => 403, 'category' => 'plan', 'retryable' => false, 'messageEn' => 'The current plan limit has been reached.', 'messageAr' => 'تم الوصول إلى حد الخطة الحالية.'],
    'PLATFORM_ACCESS_DENIED' => ['status' => 403, 'category' => 'authorization', 'retryable' => false, 'messageEn' => 'Platform access is not allowed for this account.', 'messageAr' => 'هذا الحساب غير مسموح له بدخول المنصة.'],
    'PROMOTION_INVALID_STATE' => ['status' => 409, 'category' => 'promotion', 'retryable' => false, 'messageEn' => 'This promotion cannot be changed in its current state.', 'messageAr' => 'لا يمكن تعديل هذا العرض في حالته الحالية.'],
    'RATE_LIMITED' => ['status' => 429, 'category' => 'request', 'retryable' => true, 'messageEn' => 'Too many requests. Please try again later.', 'messageAr' => 'طلبات كثيرة جدًا. حاول مرة أخرى لاحقًا.'],
    'RESOURCE_NOT_FOUND' => ['status' => 404, 'category' => 'request', 'retryable' => false, 'messageEn' => 'The requested item was not found.', 'messageAr' => 'لم يتم العثور على العنصر المطلوب.'],
    'ROOM_ACCESS_DENIED' => ['status' => 403, 'category' => 'workspace', 'retryable' => false, 'messageEn' => 'You do not have access to this room.', 'messageAr' => 'ليست لديك صلاحية الوصول إلى هذه الغرفة.'],
    'ROOM_HAS_MEMBERS' => ['status' => 409, 'category' => 'workspace', 'retryable' => false, 'messageEn' => 'Remove room members before deleting this room.', 'messageAr' => 'أزل أعضاء الغرفة قبل حذفها.'],
    'SESSION_EXPIRED' => ['status' => 401, 'category' => 'auth', 'retryable' => false, 'messageEn' => 'Your session has expired. Sign in again.', 'messageAr' => 'انتهت جلستك. سجل الدخول مرة أخرى.'],
    'SESSION_REUSE_DETECTED' => ['status' => 401, 'category' => 'auth', 'retryable' => false, 'messageEn' => 'The session was revoked for security.', 'messageAr' => 'تم إلغاء الجلسة لأسباب أمنية.'],
    'SLOT_UNAVAILABLE' => ['status' => 409, 'category' => 'booking', 'retryable' => true, 'messageEn' => 'This lesson slot is no longer available.', 'messageAr' => 'موعد الحصة لم يعد متاحًا.'],
    'STUDENT_ACCOUNT_REQUIRED' => ['status' => 403, 'category' => 'booking', 'retryable' => false, 'messageEn' => 'Use a student account to complete this action.', 'messageAr' => 'استخدم حساب طالب لإكمال هذا الإجراء.'],
    'TENANT_ACCESS_DENIED' => ['status' => 403, 'category' => 'workspace', 'retryable' => false, 'messageEn' => 'You do not have access to this organization.', 'messageAr' => 'ليست لديك صلاحية الوصول إلى هذه المؤسسة.'],
    'VALIDATION_ERROR' => ['status' => 422, 'category' => 'request', 'retryable' => false, 'messageEn' => 'Check the highlighted fields and try again.', 'messageAr' => 'راجع الحقول المطلوبة وحاول مرة أخرى.'],
    'OTP_DELIVERY_FAILED' => ['status' => 502, 'category' => 'auth', 'retryable' => true, 'messageEn' => 'The verification email could not be delivered.', 'messageAr' => 'تعذر إرسال رسالة رمز التحقق.'],
    'OTP_DELIVERY_NOT_CONFIGURED' => ['status' => 503, 'category' => 'auth', 'retryable' => false, 'messageEn' => 'Email verification delivery is not configured.', 'messageAr' => 'إرسال رموز التحقق عبر البريد غير معد بعد.'],
];
