<?php

return [
    'version' => '2026-07-24',
    'defaultWritePolicy' => 'server_confirmation_required',
    'purgeOn' => [
        'logout',
        'account_deletion',
        'workspace_removal',
        'session_revocation',
        'device_unlink',
        'security_reset',
    ],
    'datasets' => [
        'auth.profile' => [
            'endpoint' => 'GET /api/v1/auth/me',
            'scope' => 'user',
            'ttlSeconds' => 900,
            'storage' => 'secure_or_encrypted',
            'sensitivity' => 'personal',
            'offlineReadable' => true,
            'staleWhileRevalidate' => true,
            'purgeOnLogout' => true,
        ],
        'workspaces.list' => [
            'endpoint' => 'GET /api/v1/workspaces',
            'scope' => 'user',
            'ttlSeconds' => 900,
            'storage' => 'encrypted_database',
            'sensitivity' => 'tenant_membership',
            'offlineReadable' => true,
            'staleWhileRevalidate' => true,
            'purgeOnLogout' => true,
        ],
        'marketplace.courses' => [
            'endpoint' => 'GET /api/v1/public/courses',
            'scope' => 'public',
            'ttlSeconds' => 1800,
            'storage' => 'database',
            'sensitivity' => 'public',
            'offlineReadable' => true,
            'staleWhileRevalidate' => true,
            'purgeOnLogout' => false,
        ],
        'marketplace.course_detail' => [
            'endpoint' => 'GET /api/v1/public/courses/{courseSlug}',
            'scope' => 'public',
            'ttlSeconds' => 1800,
            'storage' => 'database',
            'sensitivity' => 'public',
            'offlineReadable' => true,
            'staleWhileRevalidate' => true,
            'purgeOnLogout' => false,
        ],
        'marketplace.academies' => [
            'endpoint' => 'GET /api/v1/public/academies',
            'scope' => 'public',
            'ttlSeconds' => 1800,
            'storage' => 'database',
            'sensitivity' => 'public',
            'offlineReadable' => true,
            'staleWhileRevalidate' => true,
            'purgeOnLogout' => false,
        ],
        'student.enrollments' => [
            'endpoint' => 'GET /api/v1/student/enrollments',
            'scope' => 'user',
            'ttlSeconds' => 600,
            'storage' => 'encrypted_database',
            'sensitivity' => 'course_access',
            'offlineReadable' => true,
            'staleWhileRevalidate' => true,
            'purgeOnLogout' => true,
        ],
        'organization.announcements' => [
            'endpoint' => 'GET /api/v1/organizations/{organizationId}/announcements',
            'scope' => 'organization',
            'ttlSeconds' => 600,
            'storage' => 'encrypted_database',
            'sensitivity' => 'tenant_content',
            'offlineReadable' => true,
            'staleWhileRevalidate' => true,
            'purgeOnLogout' => true,
        ],
        'organization.schedule' => [
            'endpoint' => 'GET /api/v1/organizations/{organizationId}/events',
            'scope' => 'organization',
            'ttlSeconds' => 600,
            'storage' => 'encrypted_database',
            'sensitivity' => 'tenant_calendar',
            'offlineReadable' => true,
            'staleWhileRevalidate' => true,
            'purgeOnLogout' => true,
        ],
        'notifications.inbox' => [
            'endpoint' => 'GET /api/v1/notifications',
            'scope' => 'user',
            'ttlSeconds' => 300,
            'storage' => 'encrypted_database',
            'sensitivity' => 'personal_notification',
            'offlineReadable' => true,
            'staleWhileRevalidate' => true,
            'purgeOnLogout' => true,
            'optimisticActions' => ['mark_read'],
        ],
        'content.metadata' => [
            'endpoint' => 'GET /api/v1/organizations/{organizationId}/content',
            'scope' => 'organization',
            'ttlSeconds' => 300,
            'storage' => 'encrypted_database',
            'sensitivity' => 'tenant_content_metadata',
            'offlineReadable' => true,
            'staleWhileRevalidate' => true,
            'purgeOnLogout' => true,
            'neverCacheFields' => ['viewSession.url', 'fileAsset.path'],
        ],
        'content.view_session' => [
            'endpoint' => 'GET /api/v1/organizations/{organizationId}/content/{contentId}/view-session',
            'scope' => 'organization',
            'ttlSeconds' => 0,
            'storage' => 'memory_only',
            'sensitivity' => 'signed_private_url',
            'offlineReadable' => false,
            'staleWhileRevalidate' => false,
            'purgeOnLogout' => true,
            'neverPersist' => true,
        ],
    ],
    'writeOperations' => [
        'bookings.reserve' => [
            'endpoint' => 'POST /api/v1/public/bookings',
            'offlineBehavior' => 'block_with_retry',
            'requiresServerConfirmation' => true,
        ],
        'bookings.confirm' => [
            'endpoint' => 'POST /api/v1/organizations/{organizationId}/bookings/{bookingId}/confirm',
            'offlineBehavior' => 'block_with_retry',
            'requiresServerConfirmation' => true,
        ],
        'content.upload' => [
            'endpoint' => 'POST /api/v1/organizations/{organizationId}/content',
            'offlineBehavior' => 'block_with_retry',
            'requiresServerConfirmation' => true,
        ],
        'notifications.mark_read' => [
            'endpoint' => 'POST /api/v1/notifications/{notificationId}/read',
            'offlineBehavior' => 'optimistic_reversible',
            'requiresServerConfirmation' => false,
        ],
    ],
];
